version: '3.8'
x-pysystemtrade-common:
  &pysystemtrade-common
  environment:
    IG_SERVICE_ACC_TYPE: ${IG_SERVICE_ACC_TYPE}
    IG_SERVICE_PASSWORD: ${IG_SERVICE_PASSWORD}
    IG_SERVICE_USERNAME: ${IG_SERVICE_USERNAME}
    IG_SERVICE_API_KEY: ${IG_SERVICE_API_KEY}
    IG_SERVICE_ACC_NUMBER: ${IG_SERVICE_ACC_NUMBER}
    PYSYS_PRIVATE_CONFIG_DIR: /app/pysytemtrade/config
    SCRIPT_PATH: /app/

  volumes:
    - /home/rory/dev/fx-pairs/src:/lib/volumes/python
    - ./config/:/config/
    - ./logs/pysystemtrade:/data/pysystemtrade/logs/
    - ./config/:/app/pysytemtrade/config/
  depends_on:
    &pysystemtrade-common-depends-on
    mongo:
      condition: service_healthy
    log-server:
      condition: service_healthy
    sys-init:
      condition: service_completed_successfully

services:

  mongo:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - mongo-db-volume:/data/db
    restart: always

  sys-init:
    <<: *pysystemtrade-common
    image: pairsplat
    entrypoint: [/bin/bash, -c]
    command: |
      "mkdir -p /data/pysystemtrade/logs/"
    depends_on: {}

  log-server:
    <<: *pysystemtrade-common
    image: pairsplat
    entrypoint: [/app/pysytemtrade/venv/bin/python, -m, syslogging.server, --file, /data/pysystemtrade/logs/pysystemtrade.log]
    restart: always
    depends_on:
      sys-init:
        condition: service_completed_successfully

volumes:
  mongo-db-volume:
